Add retries to module installation with r10k
Since the modules are git cloned when installed via r10k and
clones may fail due to some network glich, adding retries should
help in these cases.

We randomly hit failures during git clone in RDO promotion
jobs running on ci.centos.org, adding retries to r10k
installation to handle those random failures.

Added function 'retry_cmd' which can also be used
with other commands.

Conflicts:
  functions

Also squashed below two commits:-

Retry sealert command on failure

We randomly see issues while running sealert
in RDO puppet promotion pipeline, sealert fails with:-
"SELinux is disabled or we can't open a policy file"
As per logs selinux is enabled and selinuxfs is mounted
so seems it's some filesystem issue.

Locally was able to reproduce only with selinux disabled
or umount /sys/fs/selinux. Adding retries in hope to
fix these random failures.

Change-Id: Icb07742d328827a41132cdd6a6c2bcfa3cde11ec
(cherry picked from commit 425f454bdcb264eb80b305b67a5d4bcd4e04aadb)

Improve retry_cmd function to handle set -e

In run_tests.sh we use 'set -e' which makes
script fail as soon as error hit but we don't
want to fail in case of retries, this patch fixes it.

Change-Id: Ia33ff3dbb88317171143a43e5b1c674038187254
(cherry picked from commit ec57a35931babc9698a8399ca5c76773f069e377)

Change-Id: I5f3b94eaa5a65c76877363e9ca41684445c9cb12
(cherry picked from commit 8d5b34c5522c17f0246d208d0104c86e3325250e)

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -3,6 +3,29 @@
 # functions - puppet-openstack-integration specific functions
 #
 
+# To retry a command until it succeed for a given
+# number of retries(default to 3).
+retry_cmd() {
+  local cmd=$1
+  local total_tries=${2:-3}
+  local delay=${3:-5}
+  local retry_count=1
+  local ret_code=1
+  until [[ ${ret_code} -eq 0 || ${retry_count} -gt ${total_tries} ]]; do
+      echo Retry count:-${retry_count}, Command:-$cmd
+      set +e
+      $cmd
+      ret_code=$?
+      set -e
+      ((retry_count++))
+      sleep ${delay}
+  done
+  if [ ${ret_code} -ne 0 ]; then
+      echo Failed even after ${total_tries} retries, Exiting
+      exit ${ret_code}
+  fi
+}
+
 # Install external Puppet modules with r10k
 # Uses the following variables:
 #
@@ -14,7 +37,9 @@ if [[ "${ID,,}" = "centos" && ${VERSION_ID} = "8" ]]; then
     BASE_PUPPETFILE=Puppetfile_centos8
 fi
 install_external() {
-  PUPPETFILE=${SCRIPT_DIR}/Puppetfile1 r10k -v DEBUG puppetfile install
+  export PUPPETFILE=${SCRIPT_DIR}/Puppetfile1
+  install_cmd="r10k -v DEBUG puppetfile install"
+  retry_cmd "${install_cmd}"
 }
 
 # Install Puppet OpenStack modules from zuul checkouts
@@ -63,7 +88,9 @@ install_openstack() {
 install_all() {
   # When installing from local source, we want to install the current source
   # we're working from.
-  PUPPETFILE=${SCRIPT_DIR}/${BASE_PUPPETFILE} r10k -v DEBUG puppetfile install
+  export PUPPETFILE=${SCRIPT_DIR}/${BASE_PUPPETFILE}
+  install_cmd="r10k -v DEBUG puppetfile install"
+  retry_cmd "${install_cmd}"
   cp -a ${SCRIPT_DIR} ${PUPPETFILE_DIR}/openstack_integration
 }
 
@@ -222,7 +249,8 @@ function run_puppet() {
 
 function catch_selinux_alerts() {
     if is_fedora; then
-        $SUDO sealert -a /var/log/audit/audit.log
+        sealert_cmd="$SUDO sealert -a /var/log/audit/audit.log"
+        retry_cmd "$sealert_cmd"
         if $SUDO grep -iq 'type=AVC' /var/log/audit/audit.log; then
             echo "AVC detected in /var/log/audit/audit.log"
             source /etc/os-release
